/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package course;

import com.toedter.calendar.JCalendar;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.scene.control.DatePicker;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import java.sql.*;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Currency;
import java.util.Date;
import java.util.Locale;
import static java.lang.Math.toIntExact;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author WINDOWS 8.1
 */
public class menu extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;

    String langgananNow = "";
    static String userNow = "";
    static String password = "";
    int totalHarga = 0;

    Locale idn = new Locale("in", "ID");

    NumberFormat rupiahFormat = NumberFormat.getCurrencyInstance(idn);

    public void setLanggananNow(String s) {
        this.langgananNow = s;
    }

    public String getLanggananNow() {
        return langgananNow;
    }

    public void setUserNow(String s) {
        this.userNow = s;
    }

    public String getUserNow() {
        return userNow;
    }

    public void setPasswordNow(String s) {
        this.password = s;
    }

    public String getPasswordNow() {
        return password;
    }

    public void setTotalNow(int s) {
        this.totalHarga = s;
    }

    public int getTotalNow() {
        return totalHarga;
    }

    public void tampil() {
        try {
            DefaultTableModel tm = (DefaultTableModel) tabel_riwayat_pembayaran.getModel();
            tm.setRowCount(0);
            rs = stat.executeQuery("SELECT * FROM transaksi,user,course where user.username = '" + getUserNow() + "' and user.password = '" + getPasswordNow() + "' and user.id_user = transaksi.id_user and transaksi.id_course = course.id_course");
            while (rs.next()) {
                Object o[] = {rs.getString("id_transaksi"), rs.getString("nama_course"), rupiahFormat.format(Integer.parseInt(rs.getString("total")))};
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void editProfile() {
        try {
            String sql = "UPDATE user SET nama = '" + profileNama.getText() + "', alamat = '" + profileAlamat.getText() + "', email = '" + profileEmail.getText() + "',telepon = '" + profileTelepon.getText() + "' WHERE username = '" + getUserNow() + "' and password ='" + getPasswordNow() + "'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update!");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utama = new javax.swing.JPanel();
        course = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        webButton = new javax.swing.JButton();
        androidButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaCourse = new javax.swing.JLabel();
        hargaPerbulan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        berlanggananButton = new javax.swing.JButton();
        detailLangganan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fieldDetailTotal = new javax.swing.JTextField();
        fieldDetailNama = new javax.swing.JTextField();
        fieldDetailEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tanggalMulai = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        fieldDetailNamaCourse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldDetailTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tanggalSelesai = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        hitungButton = new javax.swing.JButton();
        courseSaya = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        profileAlamat = new javax.swing.JTextField();
        profileNama = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        profileTelepon = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        profileEmail = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        riwayatPembayaran = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_riwayat_pembayaran = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        riwayatPembayaranNama = new javax.swing.JTextField();
        riwayatPembayaranEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        riwayatPembayaranNamaCourse = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        riwayatPembayaranTelepon = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        riwayatPembayaranBulanSelesai = new javax.swing.JTextField();
        riwayatPembayaranBulanMulai = new javax.swing.JTextField();
        riwayatPembayaranTotal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        courseButton = new javax.swing.JMenu();
        courseSayaButton = new javax.swing.JMenu();
        riwayatPembayaranButton = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        utama.setLayout(new java.awt.CardLayout());

        course.setBackground(new java.awt.Color(245, 245, 245));

        jLabel4.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 71, 94));
        jLabel4.setText("Pilihan Course");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        webButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pemgrogramanWeb.jpg"))); // NOI18N
        webButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButtonActionPerformed(evt);
            }
        });
        jPanel1.add(webButton);

        androidButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pemgrogramanAndroid.jpg"))); // NOI18N
        androidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                androidButtonActionPerformed(evt);
            }
        });
        jPanel1.add(androidButton);

        jLabel3.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 71, 94));
        jLabel3.setText("Detail Course");

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 71, 94));
        jLabel5.setText("Nama Course");

        namaCourse.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        namaCourse.setForeground(new java.awt.Color(48, 71, 94));
        namaCourse.setText("-");

        hargaPerbulan.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        hargaPerbulan.setForeground(new java.awt.Color(48, 71, 94));
        hargaPerbulan.setText("-");

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 71, 94));
        jLabel8.setText("Harga Per Bulan");

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 71, 94));
        jLabel12.setText("Deskripsi");

        deskripsi.setColumns(20);
        deskripsi.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        deskripsi.setLineWrap(true);
        deskripsi.setRows(5);
        deskripsi.setEnabled(false);
        jScrollPane1.setViewportView(deskripsi);

        berlanggananButton.setBackground(new java.awt.Color(48, 71, 94));
        berlanggananButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        berlanggananButton.setForeground(new java.awt.Color(255, 255, 255));
        berlanggananButton.setText("Berlangganan");
        berlanggananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berlanggananButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courseLayout = new javax.swing.GroupLayout(course);
        course.setLayout(courseLayout);
        courseLayout.setHorizontalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(courseLayout.createSequentialGroup()
                        .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(68, 68, 68))
                                .addComponent(jLabel8))
                            .addGroup(courseLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(37, 37, 37)))
                        .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaPerbulan)
                            .addComponent(namaCourse)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(berlanggananButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        courseLayout.setVerticalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namaCourse))
                .addGap(18, 18, 18)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hargaPerbulan))
                .addGap(18, 18, 18)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(berlanggananButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        utama.add(course, "course");

        detailLangganan.setBackground(new java.awt.Color(245, 245, 245));

        jPanel2.setOpaque(false);

        fieldDetailNama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDetailNama.setEnabled(false);

        fieldDetailEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDetailEmail.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel15.setText("Total");

        jLabel6.setFont(new java.awt.Font("Raleway ExtraBold", 0, 36)); // NOI18N
        jLabel6.setText("Detail Langganan");

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel7.setText("Nama Lengkap");

        fieldDetailNamaCourse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDetailNamaCourse.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel11.setText("Telepon");

        fieldDetailTelepon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldDetailTelepon.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel9.setText("Nama Course");

        jLabel14.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel14.setText("Bulan Selesai");

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel10.setText("Email");

        tanggalSelesai.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tanggalSelesaiInputMethodTextChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(48, 71, 94));
        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Langganan Sekarang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel13.setText("Bulan Mulai");

        hitungButton.setBackground(new java.awt.Color(48, 71, 94));
        hitungButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        hitungButton.setForeground(new java.awt.Color(255, 255, 255));
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel6))
                        .addGap(56, 58, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(fieldDetailTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hitungButton))
                                    .addComponent(tanggalSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggalMulai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldDetailTelepon)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldDetailNama)
                                    .addComponent(fieldDetailNamaCourse)
                                    .addComponent(fieldDetailEmail))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldDetailNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldDetailNamaCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fieldDetailEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(fieldDetailTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldDetailTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hitungButton)))
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout detailLanggananLayout = new javax.swing.GroupLayout(detailLangganan);
        detailLangganan.setLayout(detailLanggananLayout);
        detailLanggananLayout.setHorizontalGroup(
            detailLanggananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLanggananLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        detailLanggananLayout.setVerticalGroup(
            detailLanggananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailLanggananLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        utama.add(detailLangganan, "detailLangganan");

        courseSaya.setBackground(new java.awt.Color(245, 245, 245));

        jPanel4.setOpaque(false);

        profileAlamat.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        profileNama.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel26.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel26.setText("Telepon");

        profileTelepon.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel27.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel27.setText("Nama Lengkap");

        jLabel29.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel29.setText("Alamat");

        jLabel30.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel30.setText("Email");

        profileEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(48, 71, 94));
        jButton4.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/164600.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileNama)
                            .addComponent(profileAlamat)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(profileEmail)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(profileNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(profileAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(profileTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(profileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout courseSayaLayout = new javax.swing.GroupLayout(courseSaya);
        courseSaya.setLayout(courseSayaLayout);
        courseSayaLayout.setHorizontalGroup(
            courseSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseSayaLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );
        courseSayaLayout.setVerticalGroup(
            courseSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseSayaLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        utama.add(courseSaya, "courseSaya");

        riwayatPembayaran.setBackground(new java.awt.Color(245, 245, 245));

        tabel_riwayat_pembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomer Kwitansi", "Nama Course", "Total"
            }
        ));
        tabel_riwayat_pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_riwayat_pembayaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_riwayat_pembayaran);

        jLabel16.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(48, 71, 94));
        jLabel16.setText("Riwayat Pembayaran");

        jPanel3.setOpaque(false);

        riwayatPembayaranNama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranNama.setEnabled(false);

        riwayatPembayaranEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranEmail.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel17.setText("Total");

        jLabel19.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel19.setText("Nama Lengkap");

        riwayatPembayaranNamaCourse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranNamaCourse.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel20.setText("Telepon");

        riwayatPembayaranTelepon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranTelepon.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel21.setText("Nama Course");

        jLabel22.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel22.setText("Bulan Selesai");

        jLabel23.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel23.setText("Email");

        jLabel24.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel24.setText("Bulan Mulai");

        riwayatPembayaranBulanSelesai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranBulanSelesai.setEnabled(false);

        riwayatPembayaranBulanMulai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranBulanMulai.setEnabled(false);

        riwayatPembayaranTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        riwayatPembayaranTotal.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(48, 71, 94));
        jButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(89, 89, 89)
                        .addComponent(riwayatPembayaranTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(riwayatPembayaranTelepon)
                            .addComponent(riwayatPembayaranBulanSelesai)
                            .addComponent(riwayatPembayaranBulanMulai)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(riwayatPembayaranNama)
                            .addComponent(riwayatPembayaranNamaCourse)
                            .addComponent(riwayatPembayaranEmail)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(riwayatPembayaranNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(riwayatPembayaranNamaCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(riwayatPembayaranEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(riwayatPembayaranTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(riwayatPembayaranBulanMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(riwayatPembayaranBulanSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(riwayatPembayaranTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(48, 71, 94));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print Semua Kwitansi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatPembayaranLayout = new javax.swing.GroupLayout(riwayatPembayaran);
        riwayatPembayaran.setLayout(riwayatPembayaranLayout);
        riwayatPembayaranLayout.setHorizontalGroup(
            riwayatPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayatPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(riwayatPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatPembayaranLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(riwayatPembayaranLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        riwayatPembayaranLayout.setVerticalGroup(
            riwayatPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(riwayatPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(riwayatPembayaranLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        utama.add(riwayatPembayaran, "riwayatPembayaran");

        courseButton.setText("Course");
        courseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(courseButton);

        courseSayaButton.setText("Profile Saya");
        courseSayaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseSayaButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(courseSayaButton);

        riwayatPembayaranButton.setText("Riwayat Pembayaran");
        riwayatPembayaranButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatPembayaranButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(riwayatPembayaranButton);

        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        utama.getAccessibleContext().setAccessibleName("utama");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void courseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) utama.getLayout();
        card.show(utama, "course");
    }//GEN-LAST:event_courseButtonMouseClicked

    private void courseSayaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseSayaButtonMouseClicked
        // TODO add your handling code here:
        try {
            String getData = "select * from user where username ='" + getUserNow() + "' and password = '" + getPasswordNow() + "'";
            rs = stat.executeQuery(getData);
            if (rs.next()) {
                profileNama.setText(rs.getString("nama"));
                profileAlamat.setText(rs.getString("alamat"));
                profileTelepon.setText(rs.getString("telepon"));
                profileEmail.setText(rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        CardLayout card = (CardLayout) utama.getLayout();
        card.show(utama, "courseSaya");
    }//GEN-LAST:event_courseSayaButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Logout ?", "Perhatian!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.OK_OPTION) {
            login loginf = new login();
            loginf.setVisible(true);
            this.dispose();
        } else {
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void riwayatPembayaranButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatPembayaranButtonMouseClicked
        // TODO add your handling code here:
        tampil();
        CardLayout card = (CardLayout) utama.getLayout();
        card.show(utama, "riwayatPembayaran");

    }//GEN-LAST:event_riwayatPembayaranButtonMouseClicked

    private void webButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM course WHERE id_course = 1";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                namaCourse.setText(rs.getString("nama_course"));
                String harga = rs.getString("harga_perbulan");
                int hargas = Integer.parseInt(harga);
                hargaPerbulan.setText(rupiahFormat.format(hargas));
                deskripsi.setText(rs.getString("deskripsi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_webButtonActionPerformed

    private void androidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_androidButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM course WHERE id_course = 2";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                namaCourse.setText(rs.getString("nama_course"));
                String harga = rs.getString("harga_perbulan");
                int hargas = Integer.parseInt(harga);
                hargaPerbulan.setText(rupiahFormat.format(hargas));
                deskripsi.setText(rs.getString("deskripsi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_androidButtonActionPerformed

    private void berlanggananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berlanggananButtonActionPerformed
        // TODO add your handling code here:
        setLanggananNow(namaCourse.getText());
        try {
            String sql = "SELECT * FROM user WHERE username = '" + getUserNow() + "' AND password = '" + getPasswordNow() + "' ";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                fieldDetailNama.setText(rs.getString("nama"));
                fieldDetailNamaCourse.setText(getLanggananNow());
                fieldDetailEmail.setText(rs.getString("email"));
                fieldDetailTelepon.setText(rs.getString("telepon"));
                System.out.println(rs.getString("nama"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Date d = new Date();
        tanggalMulai.setDate(d);
        tanggalSelesai.setDate(d);
        fieldDetailTotal.setText("");
        CardLayout card = (CardLayout) utama.getLayout();
        card.show(utama, "detailLangganan");


    }//GEN-LAST:event_berlanggananButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (fieldDetailTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Maaf, tekan tombol hitung dulu", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sqlcekData = "SELECT * from user, transaksi, course WHERE user.username = '" + getUserNow() + "' AND user.id_user = transaksi.id_user AND course.nama_course = '" + getLanggananNow() + "' AND course.id_course = transaksi.id_course";
                rs = stat.executeQuery(sqlcekData);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Maaf anda sudah terdaftar di course ini, silahkan tunggu konfirmasi lebih lanjut");
                } else {
                    try {
                        String sqlgetdata = "SELECT * from user,course WHERE user.username = '" + getUserNow() + "' AND course.nama_course = '" + getLanggananNow() + "'";
                        rs = stat.executeQuery(sqlgetdata);
                        rs.next();
                        SimpleDateFormat sdfm = new SimpleDateFormat("yyyy-MM-dd");
                        String sql = "INSERT INTO transaksi VALUES ('" + rs.getString("id_user") + "','" + rs.getString("id_course") + "','" + sdfm.format(tanggalMulai.getDate()) + "','" + sdfm.format(tanggalSelesai.getDate()) + "',null,'" + getTotalNow() + "')";
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Berhasil Daftar");
                        CardLayout card = (CardLayout) utama.getLayout();
                        card.show(utama, "course");
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tanggalSelesaiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tanggalSelesaiInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalSelesaiInputMethodTextChanged

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdfm = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            String tnglMulai = sdfm.format(tanggalMulai.getDate());
            String tnglSelesai = sdfm.format(tanggalSelesai.getDate());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            Date mulai = sdf.parse(tnglMulai);
            Date selesai = sdf.parse(tnglSelesai);
            long difference_In_Time = selesai.getTime() - mulai.getTime();
            long difference_In_Days = (difference_In_Time / (1000 * 60 * 60 * 24)) % 365;
            int bedahari = toIntExact(difference_In_Days);
            double totalBulan = bedahari / 30;
            double sisabulan = bedahari % 30;
            if (sisabulan > 3) {
                totalBulan = totalBulan + 1;
            }
            System.out.println(totalBulan);
            if (bedahari < 30) {
                JOptionPane.showMessageDialog(null, "Maaf, Tanggal Harus diisi dan minimal 30 Hari/1 Bulan!", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    String sql = "SELECT * FROM course WHERE nama_course = '" + getLanggananNow() + "'";
                    rs = stat.executeQuery(sql);
                    if (rs.next()) {
                        String total = rs.getString("harga_perbulan");
                        double totals = Double.valueOf(total) * totalBulan;
                        setTotalNow((int) totals);
                        fieldDetailTotal.setText(rupiahFormat.format(totals));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf, Tanggal Harus diisi dan minimal 30 Hari/1 Bulan!", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp;
            jp = JasperFillManager.fillReport(getClass().getResourceAsStream("../report1.jasper"), null, koneksi.Koneksi());
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_riwayat_pembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_riwayat_pembayaranMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel tm = (DefaultTableModel) tabel_riwayat_pembayaran.getModel();
            int selected_row = tabel_riwayat_pembayaran.getSelectedRow();
            String course = tm.getValueAt(selected_row, 1).toString();
            String sql = "select * from user,transaksi,course where user.username = '" + getUserNow() + "' and user.password = '" + getPasswordNow() + "' and user.id_user = transaksi.id_user and transaksi.id_course = course.id_course and course.nama_course = '" + course + "'";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                riwayatPembayaranNama.setText(rs.getString("nama"));
                riwayatPembayaranNamaCourse.setText(rs.getString("nama_course"));
                riwayatPembayaranEmail.setText(rs.getString("email"));
                riwayatPembayaranTelepon.setText(rs.getString("telepon"));
                riwayatPembayaranBulanMulai.setText(rs.getString("tanggal_mulai"));
                riwayatPembayaranBulanSelesai.setText(rs.getString("tanggal_selesai"));
                riwayatPembayaranTotal.setText(rupiahFormat.format(Integer.parseInt(rs.getString("total"))));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tabel_riwayat_pembayaranMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) tabel_riwayat_pembayaran.getModel();
        int selected_row = tabel_riwayat_pembayaran.getSelectedRow();
        String course = tm.getValueAt(selected_row, 0).toString();
        int i = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin", "WARNING!", JOptionPane.OK_CANCEL_OPTION);
        if (i == JOptionPane.OK_OPTION) {
            try {
                String sql = "DELETE FROM `transaksi` WHERE id_transaksi = '" + course + "'";
                stat.executeUpdate(sql);
                tampil();
                riwayatPembayaranBulanMulai.setText("");
                riwayatPembayaranBulanSelesai.setText("");
                riwayatPembayaranNama.setText("");
                riwayatPembayaranNamaCourse.setText("");
                riwayatPembayaranEmail.setText("");
                riwayatPembayaranTelepon.setText("");
                riwayatPembayaranTotal.setText("");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        editProfile();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton androidButton;
    private javax.swing.JButton berlanggananButton;
    private javax.swing.JPanel course;
    private javax.swing.JMenu courseButton;
    private javax.swing.JPanel courseSaya;
    private javax.swing.JMenu courseSayaButton;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JPanel detailLangganan;
    private javax.swing.JTextField fieldDetailEmail;
    private javax.swing.JTextField fieldDetailNama;
    private javax.swing.JTextField fieldDetailNamaCourse;
    private javax.swing.JTextField fieldDetailTelepon;
    private javax.swing.JTextField fieldDetailTotal;
    private javax.swing.JLabel hargaPerbulan;
    private javax.swing.JButton hitungButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JLabel namaCourse;
    private javax.swing.JTextField profileAlamat;
    private javax.swing.JTextField profileEmail;
    private javax.swing.JTextField profileNama;
    private javax.swing.JTextField profileTelepon;
    private javax.swing.JPanel riwayatPembayaran;
    private javax.swing.JTextField riwayatPembayaranBulanMulai;
    private javax.swing.JTextField riwayatPembayaranBulanSelesai;
    private javax.swing.JMenu riwayatPembayaranButton;
    private javax.swing.JTextField riwayatPembayaranEmail;
    private javax.swing.JTextField riwayatPembayaranNama;
    private javax.swing.JTextField riwayatPembayaranNamaCourse;
    private javax.swing.JTextField riwayatPembayaranTelepon;
    private javax.swing.JTextField riwayatPembayaranTotal;
    private javax.swing.JTable tabel_riwayat_pembayaran;
    private com.toedter.calendar.JDateChooser tanggalMulai;
    private com.toedter.calendar.JDateChooser tanggalSelesai;
    private javax.swing.JPanel utama;
    private javax.swing.JButton webButton;
    // End of variables declaration//GEN-END:variables
}
